/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/banner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["set_banner"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/comments/{id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["comment_visibility"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/posts/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolve_typo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/posts/{id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_visibility"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_list_problems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Changing the level or visibility recomputes every solver's rating. */
        patch: operations["admin_update_problem"];
        trace?: never;
    };
    "/admin/problems/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve (publish with a level) or reject (back to draft with a comment).
         *     Also used to publish official problems directly from draft.
         */
        post: operations["decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/problems/{id}/rejudge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rejudges every submission of a problem. Ratings follow the new verdicts. */
        post: operations["rejudge_problem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_reports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Closes every open report on the same target. */
        post: operations["resolve_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/{id}/rejudge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejudge_submission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/typos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_typos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspended users can still sign in but cannot submit or write. */
        post: operations["suspend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/unsuspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unsuspend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reset_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Always answers 204 so it cannot be used to probe for accounts. */
        post: operations["reset_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resend_verification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Personal data is erased at once. Submissions and posts stay, shown as a
         *     deleted user; the handle is locked forever.
         */
        post: operations["delete_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/handle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Once per 90 days. The old handle is locked for 180 days and redirects. */
        post: operations["change_handle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Also signs out every other session. */
        post: operations["change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_settings"];
        trace?: never;
    };
    "/my/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_mine"];
        put?: never;
        post: operations["create_problem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_mine"];
        put: operations["update_problem"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my/problems/{id}/request-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["request_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my/problems/{id}/testcases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upload_testcases"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my/problems/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queues the reference-solution check: every case must pass within half
         *     the time limit.
         */
        post: operations["validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my/problems/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["withdraw_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_post"];
        put?: never;
        post?: never;
        /** Authors and admins can remove (hide) a post. */
        delete: operations["delete_post"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_problems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_problem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_posts"];
        put?: never;
        post: operations["create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** One submission per user per 10 seconds; refused while the queue is full. */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ranking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hides the target automatically once enough distinct users report it. */
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["site_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_submissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_submission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminProblemPatch: {
            /** Format: int32 */
            level?: number | null;
            /** @description DRAFT, REVIEW or PUBLIC */
            status?: string | null;
        };
        AdminProblemRow: {
            author?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            proposed_level?: number | null;
            /** Format: int32 */
            solved_count: number;
            source: string;
            status: string;
            /** Format: int64 */
            testcase_count: number;
            title: string;
            validation_status?: string | null;
        };
        AdminUserRow: {
            /** Format: date-time */
            created_at: string;
            email?: string | null;
            email_verified: boolean;
            handle?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            rating: number;
            role: string;
            suspend_reason?: string | null;
            suspended: boolean;
        };
        BannerBody: {
            /** @description Empty to clear. */
            text: string;
        };
        CommentBody: {
            body: string;
            code?: string | null;
            code_language?: string | null;
        };
        CommentView: {
            body: string;
            code?: string | null;
            /** @description Code exists but the viewer has not solved the problem. */
            code_hidden: boolean;
            code_language?: string | null;
            /** Format: date-time */
            created_at: string;
            handle?: string | null;
            hidden: boolean;
            /** Format: int64 */
            id: number;
            is_mine: boolean;
        };
        Created: {
            /** Format: int64 */
            id: number;
        };
        CreatedProblem: {
            /** Format: int32 */
            id: number;
        };
        Decision: {
            approve: boolean;
            comment?: string | null;
            /**
             * Format: int32
             * @description Final level; required when approving.
             */
            level?: number | null;
        };
        DeleteBody: {
            password: string;
        };
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /** @description Stable machine-readable code, e.g. `NOT_FOUND`. */
            code: string;
            /** @description For `HANDLE_MOVED`: the handle to go to instead. */
            location?: string | null;
            /** @description Korean message for display. */
            message: string;
        };
        GroupInfo: {
            color: string;
            /** Format: int32 */
            max_level: number;
            /** Format: int32 */
            min_level: number;
            name: string;
            symbol: string;
        };
        HandleBody: {
            handle: string;
        };
        LanguageInfo: {
            id: string;
            name: string;
        };
        LoginBody: {
            /** @description Handle or email. */
            login: string;
            password: string;
        };
        /** @description `GET /me` payload. */
        Me: {
            default_language?: string | null;
            email: string;
            email_verified: boolean;
            handle: string;
            /** Format: date-time */
            handle_changed_at?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            rating: number;
            role: string;
            suspend_reason?: string | null;
            suspended: boolean;
            /** Format: int32 */
            tier: number;
        };
        MyProblem: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            memory_limit_mb: number;
            /** Format: int32 */
            proposed_level?: number | null;
            reviews: components["schemas"]["ReviewEntry"][];
            solution_code?: string | null;
            solution_language?: string | null;
            source: string;
            statement: components["schemas"]["Statement"];
            status: string;
            testcases: components["schemas"]["TestcaseInfo"][];
            /** Format: int32 */
            time_limit_ms: number;
            title: string;
            /** Format: date-time */
            validated_at?: string | null;
            validation_message?: string | null;
            validation_status?: string | null;
        };
        MyProblemRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            id: number;
            /** @description Last review comment, e.g. the reason for a rejection. */
            last_review?: string | null;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            proposed_level?: number | null;
            source: string;
            status: string;
            title: string;
            validation_status?: string | null;
        };
        Overview: {
            /**
             * Format: int64
             * @description Judged submissions in the last 24 hours.
             */
            judged_24h: number;
            /** Format: int64 */
            judging: number;
            /** Format: int64 */
            open_reports: number;
            /** Format: int64 */
            open_typos: number;
            /** Format: int64 */
            pending_reviews: number;
            /** Format: int64 */
            public_problems: number;
            queue_length: number;
            queue_limit: number;
            /**
             * Format: double
             * @description SE share of the last 24 hours' judged submissions, 0..=1.
             */
            system_error_rate_24h: number;
            /** Format: int64 */
            users: number;
        };
        Page_PostSummary: {
            items: {
                /** Format: int32 */
                comment_count: number;
                /** Format: date-time */
                created_at: string;
                handle?: string | null;
                hidden: boolean;
                /** Format: int64 */
                id: number;
                /** @description QUESTION, COUNTEREXAMPLE or TYPO */
                kind: string;
                /** Format: int32 */
                problem_id: number;
                resolved: boolean;
                title: string;
            }[];
            /** @description Pass as `cursor` to get the next page; absent on the last page. */
            next_cursor?: string | null;
        };
        Page_ProblemSummary: {
            items: {
                /** Format: int32 */
                id: number;
                /** Format: int32 */
                level: number;
                /** @description Viewer's state: SOLVED, TRIED or null. */
                my_state?: string | null;
                /** Format: int32 */
                solved_count: number;
                source: string;
                /** Format: int32 */
                submission_count: number;
                title: string;
            }[];
            /** @description Pass as `cursor` to get the next page; absent on the last page. */
            next_cursor?: string | null;
        };
        Page_RankingRow: {
            items: {
                handle: string;
                /** Format: int64 */
                id: number;
                /** Format: int64 */
                rank: number;
                /** Format: int32 */
                rating: number;
                /** Format: int64 */
                solved_count: number;
                /** Format: int32 */
                tier: number;
            }[];
            /** @description Pass as `cursor` to get the next page; absent on the last page. */
            next_cursor?: string | null;
        };
        Page_SubmissionRow: {
            items: {
                /** Format: int32 */
                code_length: number;
                /** Format: date-time */
                created_at: string;
                /** @description Null for a deleted account ("탈퇴한 사용자"). */
                handle?: string | null;
                /** Format: int64 */
                id: number;
                language: string;
                /** Format: int32 */
                memory_kb?: number | null;
                /** Format: int32 */
                problem_id: number;
                problem_title: string;
                status: string;
                /** Format: int32 */
                time_ms?: number | null;
            }[];
            /** @description Pass as `cursor` to get the next page; absent on the last page. */
            next_cursor?: string | null;
        };
        PasswordBody: {
            current_password: string;
            new_password: string;
        };
        PostBody: {
            body: string;
            code?: string | null;
            code_language?: string | null;
            kind: string;
            title: string;
        };
        PostSummary: {
            /** Format: int32 */
            comment_count: number;
            /** Format: date-time */
            created_at: string;
            handle?: string | null;
            hidden: boolean;
            /** Format: int64 */
            id: number;
            /** @description QUESTION, COUNTEREXAMPLE or TYPO */
            kind: string;
            /** Format: int32 */
            problem_id: number;
            resolved: boolean;
            title: string;
        };
        PostView: {
            body: string;
            code?: string | null;
            code_hidden: boolean;
            code_language?: string | null;
            comments: components["schemas"]["CommentView"][];
            /** Format: date-time */
            created_at: string;
            handle?: string | null;
            hidden: boolean;
            /** Format: int64 */
            id: number;
            is_mine: boolean;
            kind: string;
            /** Format: int32 */
            problem_id: number;
            problem_title: string;
            resolved: boolean;
            title: string;
        };
        ProblemDetail: {
            /**
             * Format: double
             * @description Share of judged submissions that were AC, 0..=1.
             */
            accept_rate: number;
            author?: string | null;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            memory_limit_kb: number;
            my_state?: string | null;
            /** Format: date-time */
            published_at?: string | null;
            /** Format: int32 */
            solved_count: number;
            source: string;
            statement: components["schemas"]["Statement"];
            /** @description DRAFT, REVIEW or PUBLIC. Non-public problems are visible to the author and admins only. */
            status: string;
            /** Format: int32 */
            submission_count: number;
            /** Format: int32 */
            time_limit_ms: number;
            title: string;
        };
        ProblemInput: {
            /** @description Required on create: agrees to the problem authoring terms. */
            agree_terms?: boolean;
            /** Format: int32 */
            memory_limit_mb: number;
            /**
             * Format: int32
             * @description Author's suggested level 0..=30; an admin sets the final level.
             */
            proposed_level?: number | null;
            solution_code?: string | null;
            solution_language?: string | null;
            statement: components["schemas"]["Statement"];
            /** Format: int32 */
            time_limit_ms: number;
            title: string;
        };
        ProblemRef: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            level: number;
            title: string;
        };
        ProblemSummary: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            level: number;
            /** @description Viewer's state: SOLVED, TRIED or null. */
            my_state?: string | null;
            /** Format: int32 */
            solved_count: number;
            source: string;
            /** Format: int32 */
            submission_count: number;
            title: string;
        };
        Profile: {
            /** @description Tried but not solved. */
            failed: components["schemas"]["ProblemRef"][];
            handle: string;
            /** Format: date-time */
            joined_at: string;
            /** @description Solved count per level, index 0..=30. */
            level_counts: number[];
            /**
             * Format: int64
             * @description Rating needed for the next tier; null at the top.
             */
            next_tier_rating?: number | null;
            /**
             * Format: int64
             * @description 1-based position in the ranking.
             */
            rank: number;
            /** Format: int32 */
            rating: number;
            solved: components["schemas"]["ProblemRef"][];
            /** Format: int64 */
            submission_count: number;
            /** Format: int32 */
            tier: number;
        };
        RankingRow: {
            handle: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            rank: number;
            /** Format: int32 */
            rating: number;
            /** Format: int64 */
            solved_count: number;
            /** Format: int32 */
            tier: number;
        };
        Recomputed: {
            /** @description Users whose rating was recomputed. */
            users: number;
        };
        ReportBody: {
            reason: string;
            /** Format: int64 */
            target_id: number;
            /** @description POST or COMMENT */
            target_type: string;
        };
        ReportRow: {
            /** Format: date-time */
            created_at: string;
            excerpt?: string | null;
            /** Format: int64 */
            id: number;
            /**
             * Format: int64
             * @description Post the target belongs to, for linking.
             */
            post_id?: number | null;
            reason: string;
            /** Format: int64 */
            report_count: number;
            reporter?: string | null;
            target_hidden?: boolean | null;
            /** Format: int64 */
            target_id: number;
            target_type: string;
        };
        Requeued: {
            submissions: number;
        };
        ResetConfirmBody: {
            password: string;
            token: string;
        };
        ResetRequestBody: {
            email: string;
        };
        ResolveBody: {
            /** @description true hides the target, false restores it. */
            hide: boolean;
        };
        ReviewEntry: {
            comment?: string | null;
            /** Format: date-time */
            created_at: string;
            decision: string;
            reviewer?: string | null;
        };
        Sample: {
            input: string;
            output: string;
        };
        SettingsBody: {
            /** @description Language id, or null to clear. */
            default_language?: string | null;
        };
        SignupBody: {
            /** @description Must be true: agrees to the terms of service and privacy policy. */
            agree_terms: boolean;
            email: string;
            handle: string;
            password: string;
        };
        SiteInfo: {
            /** @description Maintenance notice shown at the top of every page. */
            banner?: string | null;
            groups: components["schemas"]["GroupInfo"][];
            languages: components["schemas"]["LanguageInfo"][];
            /** Format: int64 */
            tier_coefficient: number;
        };
        /** @description Statement sections, Markdown with KaTeX math. */
        Statement: {
            hint?: string | null;
            input: string;
            legend: string;
            output: string;
            samples?: components["schemas"]["Sample"][];
        };
        SubmissionDetail: components["schemas"]["SubmissionRow"] & {
            /** @description Present when the viewer may read it: the author, admins, and users who solved the problem. */
            code?: string | null;
            /** @description Compile output, for the author of a CE submission. */
            compile_message?: string | null;
            is_mine: boolean;
            /** Format: date-time */
            judged_at?: string | null;
        };
        SubmissionRow: {
            /** Format: int32 */
            code_length: number;
            /** Format: date-time */
            created_at: string;
            /** @description Null for a deleted account ("탈퇴한 사용자"). */
            handle?: string | null;
            /** Format: int64 */
            id: number;
            language: string;
            /** Format: int32 */
            memory_kb?: number | null;
            /** Format: int32 */
            problem_id: number;
            problem_title: string;
            status: string;
            /** Format: int32 */
            time_ms?: number | null;
        };
        SubmitBody: {
            code: string;
            language: string;
        };
        SubmitResult: {
            /** Format: int64 */
            id: number;
        };
        SuspendBody: {
            reason: string;
        };
        TestcaseInfo: {
            /** Format: int32 */
            idx: number;
            /** Format: int64 */
            input_size: number;
            is_sample: boolean;
            /** Format: int64 */
            output_size: number;
        };
        TestcaseUpload: {
            /**
             * Format: binary
             * @description Zip of `1.in`, `1.out`, `2.in`, `2.out`, ... (samples are added automatically).
             */
            file: string;
        };
        TokenBody: {
            token: string;
        };
        TypoRow: {
            /** Format: date-time */
            created_at: string;
            handle?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            problem_id: number;
            title: string;
        };
        VisibilityBody: {
            hidden: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    set_banner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BannerBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    comment_visibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisibilityBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    resolve_typo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_visibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisibilityBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_list_problems: {
        parameters: {
            query?: {
                /** @description DRAFT, REVIEW or PUBLIC */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProblemRow"][];
                };
            };
        };
    };
    admin_update_problem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminProblemPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recomputed"];
                };
            };
        };
    };
    decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    rejudge_problem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Requeued"];
                };
            };
        };
    };
    list_reports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRow"][];
                };
            };
        };
    };
    resolve_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejudge_submission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Requeued"];
                };
            };
        };
    };
    list_typos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypoRow"][];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: {
                /** @description Part of a handle or email. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserRow"][];
                };
            };
        };
    };
    suspend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuspendBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unsuspend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetConfirmBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reset_request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetRequestBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resend_verification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    verify_email: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    change_handle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandleBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyProblemRow"][];
                };
            };
        };
    };
    create_problem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedProblem"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_mine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyProblem"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_problem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemInput"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    request_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    upload_testcases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["TestcaseUpload"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    withdraw_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostView"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Created"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_problems: {
        parameters: {
            query?: {
                /** @description id (default), level, solved */
                sort?: string;
                /** @description asc (default for id) or desc */
                order?: string;
                /** @description Group name: unrated, natural, integer, rational, real, complex, quaternion */
                group?: string;
                /** @description Title search, or an exact problem number. */
                q?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProblemSummary"];
                };
            };
        };
    };
    get_problem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_posts: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PostSummary"];
                };
            };
        };
    };
    create_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Created"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResult"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    ranking: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RankingRow"];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    site_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteInfo"];
                };
            };
        };
    };
    list_submissions: {
        parameters: {
            query?: {
                problem_id?: number;
                handle?: string;
                /** @description AC, WA, ... */
                status?: string;
                language?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SubmissionRow"];
                };
            };
        };
    };
    get_submission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
