[package]
name = "acc-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
acc-core = { version = "0.1.0", path = "../acc-core", features = ["db", "storage"] }
anyhow = "1.0.104"
argon2 = "0.6.0"
axum = { version = "0.8.9", features = ["multipart", "macros"] }
axum-extra = { version = "0.12.6", features = ["cookie"] }
base64 = "0.23.1"
chrono = { version = "0.4.45", features = ["serde"] }
hex = "0.4.3"
object_store = { version = "0.14.2", features = ["aws"] }
rand = "0.10.3"
redis = { version = "1.2.2", features = ["tokio-comp", "connection-manager"] }
reqwest = { version = "0.13.5", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "chrono", "json", "migrate"] }
thiserror = "2.0.21"
time = "0.3.45"
tokio = { version = "1.53.1", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.7.1", features = ["trace", "limit"] }
tower_governor = { version = "0.8.0", default-features = false, features = ["axum"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
utoipa = { version = "5.5.0", features = ["axum_extras", "chrono"] }
utoipa-axum = "0.2.0"
zip = "7.2.0"
